my_app/my_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include('photo_app.urls')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_app/photo_app/urls.py
from django.urls import path, include

from . import views

app_name = 'photo_app'

urlpatterns = [
    path('', views.index, name='main'),  # photo_app:main
    path('images/', views.view_pictures, name='pictures'),
    path('upload/', views.upload, name='upload'),
    path('images/edit/<int:img_id>', views.edit, name='edit'),
    path('images/remove/<int:img_id>', views.remove, name='remove'),
]

my_app/users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

# from .forms import LogingForm
from .forms import LoginForm
from .views import RegisterView

app_name = 'users'


urlpatterns = [
    path('registration/', RegisterView.as_view(), name='signup'),
    path('login/',
         LoginView.as_view(template_name='users/login.html', form_class=LoginForm, redirect_authenticated_user=True),
         name='signin'),
    path('logout/', LogoutView.as_view(template_name='users/logout.html'), name='logout'),
]

my_app/photo_app/models.py
import os
from uuid import uuid4
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from django.db import models


def validate_file_size(value):
    filesize = value.size

    if filesize > 10048576:
        raise ValidationError('Максимальний розмір файлу, який можна завантажити - 10MB')
    else:
        return value


def upload_image(instance, filename):
    if instance.user:
        upload_to = instance.user.username
    else:
        upload_to = 'uploads'
    ext = filename.split('.')[-1]
    filename = f'{uuid4().hex}.{ext}'
    return os.path.join(upload_to, filename)


# Create your models here.
class Picture(models.Model):
    description = models.CharField(max_length=200)
    path = models.ImageField(upload_to=upload_image, validators=[validate_file_size])
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None, null=True, blank=True)

my_app/photo_app/forms.py
from django.forms import ModelForm, ImageField, CharField, TextInput, FileInput
from .models import Picture


class PictureForm(ModelForm):
    description = CharField(max_length=200, min_length=5, widget=TextInput(attrs={'class': 'form-control'}))
    path = ImageField(widget=FileInput(attrs={'class': 'form-control', "accept": "image/*"}))

    class Meta:
        model = Picture
        fields = ['description', 'path']

my_app/users/forms.py
from django.forms import ModelForm, CharField, TextInput, EmailField, EmailInput, PasswordInput
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


class RegisterForm(UserCreationForm):
    username = CharField(max_length=16, required=True, widget=TextInput(attrs={'class': "form-control"}))
    first_name = CharField(max_length=25, widget=TextInput(attrs={'class': "form-control"}))
    last_name = CharField(max_length=25, widget=TextInput(attrs={'class': "form-control"}))
    email = EmailField(max_length=50, required=True, widget=EmailInput(attrs={'class': "form-control"}))
    password1 = CharField(max_length=12, min_length=6, required=True,
                          widget=PasswordInput(attrs={'class': "form-control"}))
    password2 = CharField(max_length=12, min_length=6, required=True,
                          widget=PasswordInput(attrs={'class': "form-control"}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')


class LoginForm(AuthenticationForm):
    username = CharField(max_length=16, required=True, widget=TextInput(attrs={'class': "form-control"}))
    password = CharField(max_length=12, min_length=6, required=True, widget=PasswordInput(attrs={'class': "form-control"}))

    class Meta:
        model = User
        fields = ('username', 'password')

my_app/photo_app/views.py
import os
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.conf import settings
# Create your views here.
from .models import Picture
from .forms import PictureForm


def index(request):
    return render(request, 'photo_app/index.html', context={'title': 'Main Page'})


@login_required
def view_pictures(request):
    pictures = Picture.objects.filter(user=request.user).all()
    return render(request, 'photo_app/pictures.html', context={'title': 'Pictures Page', 'pictures': pictures})


@login_required
def upload(request):
    form = PictureForm(instance=Picture())
    if request.method == "POST":
        form = PictureForm(request.POST, request.FILES, instance=Picture())
        if form.is_valid():
            picture = form.save(commit=False)
            picture.user = request.user
            picture.save()
            return redirect(to='photo_app:pictures')
    return render(request, 'photo_app/upload.html', context={'title': 'Upload Page', 'form': form})


@login_required
def edit(request, img_id):
    if request.method == "POST":
        description = request.POST.get("description")
        Picture.objects.filter(pk=img_id, user=request.user).update(description=description)
        return redirect(to="photo_app:pictures")

    pic = Picture.objects.filter(pk=img_id, user=request.user).first()
    return render(request, "photo_app/change.html", context={"title": "Change description", "pic": pic})


@login_required
def remove(request, img_id):
    pic = Picture.objects.filter(pk=img_id, user=request.user)
    try:
        os.unlink(os.path.join(settings.MEDIA_ROOT, str(pic.first().path)))
    except OSError as e:
        print(e)
    pic.delete()
    return redirect(to="photo_app:pictures")

my_app/photo_app/templates/photo_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

    {% load static %}
    <link rel="stylesheet" href="{% static 'photo_app/style.css' %}">
    <title>{{title}}</title>
</head>
<body>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link active" aria-current="page" href="{% url 'photo_app:main' %}">Home</a>
        {% if user.is_authenticated %}
        <a class="nav-link" href="{% url 'photo_app:pictures' %}">Pictures</a>
        <a class="nav-link" href="{% url 'photo_app:upload' %}">Upload</a>
        <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
        {% else %}
        <a class="nav-link" href="{% url 'users:signup' %}">Registration</a>
        <a class="nav-link" href="{% url 'users:signin' %}">Login</a>
        {% endif %}
      </div>
    </div>
  </div>
</nav>
{% block content%}
{% endblock %}



</body>
</html>

my_app/photo_app/templates/photo_app/change.html
{% extends 'photo_app/base.html' %}

{% block content %}
<div class="container">

    <form action="{% url 'photo_app:edit' pic.id %}" method="post">
        {% csrf_token %}
        <img src="{{pic.path.url}}" width=360 alt="image">
        <div class="mb-3">
            <label>Change description</label>
          <input type="text" class="form-control" value="{{pic.description}}" name="description">
        </div>
        <div class="mb-3">
            <button type="submit" class="btn btn-primary">Send</button>
            <button type="reset" class="btn btn-secondary">Reset</button>
        </div>
    </form>

</div>

{% endblock %}

my_app/photo_app/templates/photo_app/index.html
{%extends 'photo_app/base.html' %}

{% block content %}

 <div class="container mt-3">
    <h1>Hello world</h1>
</div>

{% endblock %}

my_app/photo_app/templates/photo_app/pictures.html
{%extends 'photo_app/base.html' %}

{% block content %}

 <div class="container mt-3">
    <h1>Pictures</h1>
</div>
<div calss="container">
    <div class="row mt-3">
        {% for pic in pictures %}
        <div calss="col-md-3">
            <div class="card" style="width: 18rem;">
              <img src="{{pic.path.url}}" class="card-img-top" alt="...">
              <div class="card-body">
                <h5 class="card-title">{{pic.description}}</h5>
                <a href="{% url 'photo_app:edit' pic.id %}" class="btn btn-info">Change description</a>
                <a href="{% url 'photo_app:remove' pic.id %}" class="btn btn-danger">Delete picture</a>
              </div>
            </div>
        </div>
        {% endfor %}
    </div>

</div>



{% endblock %}

my_app/photo_app/templates/photo_app/upload.html
{%extends 'photo_app/base.html' %}

{% block content %}

 <div class="container mt-3">
    <h1>Upload Pictures</h1>
    {%if form.errors and form.non_field_errors %}
    <span class="alert alert-danger" role="alert">{{form.non_field_errors}}</span>
    {% endif %}
    <form action="{% url 'photo_app:upload' %}" method='post' enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-3">
          <label  class="form-label">Description
          {{ form.description }}
          </label>
          <span>{{form.errors.description}}</span>
        </div>
        <div class="mb-3">
          <label class="form-label">Upload
          {{ form.path }}
          </label>
          <span>{{form.errors.path}}</span>
        </div>
        <div class="mb-3">
            <button type="submit" class="btn btn-primary">Send</button>
            <button type="reset" class="btn btn-primary">Reset</button>
        </div>
    </form>
 </div>
{% endblock %}

my_app/users/templates/users/login.html
{% extends "photo_app/base.html" %}
{% block content %}
 <div class="container mt-3">
    <h2 class="mb-3">User Login</h2>
    {% if messages %}
    <div class="messages">
        {% for message in messages %}
        <span {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}}>{{ message }} </span>
        {% endfor %}
    </div>
    {% endif %}
    {%if form.errors and form.non_field_errors %}
    <span class="alert alert-danger" role="alert">{{form.non_field_errors}}</span>
    {% endif %}
    <form  method='post'>
        {% csrf_token %}
        <div class="mb-3">
          <label  class="form-label">Username
          {{ form.username }}
          </label>
          <span>{{form.errors.username}}</span>
        </div>

       <div class="mb-3">
          <label  class="form-label">Password
          {{ form.password }}
          </label>
          <span>{{form.errors.password}}</span>
        </div>

       <div class="mb-3">
            <button type="submit" class="btn btn-primary">Send</button>
            <button type="reset" class="btn btn-primary">Reset</button>
        </div>
    </form>
 </div>

{% endblock %}

my_app/users/templates/users/logout.html
{% extends "quotes/base.html" %}
{% block content %}
 <div class="container mt-3">
    <h2 class="mb-3">Come Again!</h2>
 <div>
{% endblock %}

my_app/users/templates/users/register.html
{% extends "quotes/base.html" %}
{% block content %}
 <div class="container mt-3">
    <h2>Register User</h2>
    {%if form.errors and form.non_field_errors %}
    <span class="alert alert-danger" role="alert">{{form.non_field_errors}}</span>
    {% endif %}
    <form  method='post'>
        {% csrf_token %}
        <div class="mb-3">
          <label  class="form-label">Username
          {{ form.username }}
          </label>
          <span>{{form.errors.username}}</span>
        </div>
       <div class="mb-3">
          <label  class="form-label">First name
          {{ form.first_name }}
          </label>
          <span>{{form.errors.first_name}}</span>
        </div>
        <div class="mb-3">
          <label  class="form-label">Second name
          {{ form.last_name }}
          </label>
          <span>{{form.errors.last_name}}</span>
        </div>
       <div class="mb-3">
          <label  class="form-label">Email
          {{ form.email }}
          </label>
          <span>{{form.errors.email}}</span>
       </div>
       <div class="mb-3">
          <label  class="form-label">Password
          {{ form.password1 }}
          </label>
          <span>{{form.errors.password1}}</span>
        </div>
       <div class="mb-3">
          <label  class="form-label">Repeat password
          {{ form.password2 }}
          </label>
          <span>{{form.errors.password2}}</span>
       </div>
       <div class="mb-3">
            <button type="submit" class="btn btn-primary">Send</button>
            <button type="reset" class="btn btn-primary">Reset</button>
        </div>
    </form>
 </div>

{% endblock %}}